### ISSUE TITLE
Uncaught TypeError: i.queryManager.mutationStore.getStore is not a function

### ISSUE THREAD

**Issue by hinok** [apollographql/apollo-client-devtools#687]
**Update**

After enabling locally built older version of the extension and basically switching between versions `3.0.5` and `2.3.5`, it's fixed 😱

What's funny... I got the old UI while having enabled `3.0.5` in the `chrome://extensions/`.
Does chrome have some cache for enabled extensions? Super weird...

I'm closing the issue as it seems that the extension is working fine.

---

**Intended outcome:**

Working extension.

**Actual outcome:**

The extension doesn't work.
Error is printed in the `console`

```
VM2204 backend.js:formatted:14968 Uncaught TypeError: i.queryManager.mutationStore.getStore is not a function
    at t.<anonymous> (VM2204 backend.js:formatted:14968)
    at t.n.emit (VM2204 backend.js:formatted:10103)
    at VM2204 backend.js:formatted:14766
    at t (VM2204 backend.js:formatted:14865)
```

The error points to this line of code

```
mutations: i.queryManager ? i.queryManager.mutationStore.getStore() : {},
```

**How to reproduce the issue:**

 - Extension version: `3.0.5`
 - @apollo/client version: `3.4.9`

I'm not able to create a reproduction now.
It's working fine with `apollo-client-devtools 2.3.5`. 

**Desktop (please complete the following information):**
 - OS: `macOS Big Sur 11.3.1`
 - Browser: `Chrome`
 - Browser version: `92.0.4515.159 (x86_64)`
