### ISSUE TITLE
i.queryManager.mutationStore.getStore is not a function

### ISSUE THREAD

**Issue by AdrienLemaire** [apollographql/apollo-client-devtools#301]
Started seeing this error on the chrome console:
![](https://i.imgur.com/sy8sy9I.png)

My application seems to work as usual.
The "Watched queries", "Mutation log" and "cache" tabs of chrome apollo devtools extension are all empty.

Using devtools 2.3.1 and `@apollo/client@3.3.0-beta.13` 

Edit: The error doesn't show up when downgrading to `@apollo/client@3.3.0-beta.12`.

**Comment by jcreighton** [comment]
Hello! That's due to this change: https://github.com/apollographql/apollo-client/pull/7161 Let me see if I can get this change into our next devtools release so we can keep them working with Apollo Client 3.3!
